/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        dark: 'rgb(var(--color-dark) / <alpha-value>)',
        light: 'rgb(var(--color-light) / <alpha-value>)',
        'dark-gray': 'rgb(var(--color-surface-dark) / <alpha-value>)',
        'custom-blue': {
          DEFAULT: 'rgb(var(--color-accent) / <alpha-value>)',
          100: 'rgb(var(--color-accent-soft) / <alpha-value>)',
          200: 'rgb(var(--color-accent-muted) / <alpha-value>)',
          400: 'rgb(var(--color-accent-bright) / <alpha-value>)',
          500: 'rgb(var(--color-accent) / <alpha-value>)',
          600: 'rgb(var(--color-accent-strong) / <alpha-value>)',
          800: 'rgb(var(--color-accent-deep) / <alpha-value>)',
        },
        'custom-gray': {
          DEFAULT: 'rgb(var(--color-muted) / <alpha-value>)',
          200: 'rgb(var(--color-border-soft) / <alpha-value>)',
          300: 'rgb(var(--color-muted-light) / <alpha-value>)',
          400: 'rgb(var(--color-muted) / <alpha-value>)',
          500: 'rgb(var(--color-muted-strong) / <alpha-value>)',
          600: 'rgb(var(--color-text-muted) / <alpha-value>)',
          700: 'rgb(var(--color-text-body) / <alpha-value>)',
          900: 'rgb(var(--color-text-strong) / <alpha-value>)',
        },
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-elevated': 'rgb(var(--color-surface-elevated) / <alpha-value>)',
        'surface-muted': 'rgb(var(--color-surface-muted) / <alpha-value>)',
        'surface-glass': 'rgb(var(--color-surface-glass) / <alpha-value>)',
        'border-soft': 'rgb(var(--color-border-soft) / <alpha-value>)',
        'border-strong': 'rgb(var(--color-border-strong) / <alpha-value>)',
        'text-body': 'rgb(var(--color-text-body) / <alpha-value>)',
        'text-muted': 'rgb(var(--color-text-muted) / <alpha-value>)',
        'text-strong': 'rgb(var(--color-text-strong) / <alpha-value>)',
        accent: 'rgb(var(--color-accent) / <alpha-value>)',
        'accent-hover': 'rgb(var(--color-accent-strong) / <alpha-value>)',
        'accent-soft': 'rgb(var(--color-accent-soft) / <alpha-value>)',
        violet: 'rgb(var(--color-violet) / <alpha-value>)',
        magenta: 'rgb(var(--color-magenta) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        danger: 'rgb(var(--color-danger) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
      },
      boxShadow: {
        control: 'var(--shadow-control)',
        glass: 'var(--shadow-glass)',
        glow: 'var(--shadow-glow)',
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
      },
      borderRadius: {
        brand: 'var(--radius-brand)',
        control: 'var(--radius-control)',
        pill: 'var(--radius-pill)',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        outfit: ['Outfit', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
